export const columns = [
  'Dataset',
  'Medium',
  'Samp #',
  'Target/NTA',
  'State',
  'City',
  'ZIP',
  'Lat',
  'Long',
  'Sample Datetime',
  'Analysis Datetime',
  'Chemical Name',
  'DTXSID',
  'Chemical Formula',
  'Molecular Mass',
  'Retention Time',
  'ID Confidence Level (Schyhmanski scale)',
  'Abundance',
  'Units',
  'MRL or D',
]
